In [24]:
import pandas as pd

In [25]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [26]:
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [27]:
df.tail()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1944,Zimbabwe,2016,3.735,7.984,0.768,54.4,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.0,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.6,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.8,0.643,-0.009,0.789,0.703,0.346

In [28]:
df.shape

(1949, 11)

In [29]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [30]:
df.sample(8)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
136,Belarus,2009,5.564,9.681,0.908,62.00,0.679,-0.203,0.676,0.566,0.223
627,Ghana,2012,5.057,8.397,0.685,54.86,0.679,0.040,0.898,0.760,0.152
446,Czech Republic,2017,6.790,10.558,0.901,69.80,0.832,-0.177,0.867,0.739,0.227
958,Latvia,2011,4.967,10.029,0.836,64.86,0.564,-0.002,0.934,0.563,0.222
666,Guinea,2013,3.902,7.619,0.567,50.66,0.693,0.091,0.815,0.600,0.348
1693,Tajikistan,2017,5.829,8.036,0.663,63.80,0.832,0.124,0.718,0.603,0.278
338,Chile,2017,6.320,10.072,0.880,69.80,0.790,-0.020,0.836,0.838,0.291
432,Cyprus,2016,5.795,10.506,0.786,73.30,0.756,-0.030,0.898,0.742,0.336

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1949 non-null   object
 1   year                              1949 non-null   int64
 2   Life Ladder                       1949 non-null   float64
 3   Log GDP per capita                1913 non-null   float64
 4   Social support                    1936 non-null   float64
 5   Healthy life expectancy at birth  1894 non-null   float64
 6   Freedom to make life choices      1917 non-null   float64
 7   Generosity                        1860 non-null   float64
 8   Perceptions of corruption         1839 non-null   float64
 9   Positive affect                   1927 non-null   float64
 10  Negative affect                   1933 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 167.6+ KB

In [32]:
df.dtypes

Country name                         object
year                                  int64
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [33]:
 df["Country name"].dtype

dtype('O')

In [34]:
df.describe()

,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
count,1949.000000,1949.000000,1913.000000,1936.000000,1894.000000,1917.000000,1860.000000,1839.000000,1927.000000,1933.000000
mean,2013.216008,5.466705,9.368453,0.812552,63.359374,0.742558,0.000103,0.747125,0.710003,0.268544
std,4.166828,1.115711,1.154084,0.118482,7.510245,0.142093,0.162215,0.186789,0.107100,0.085168
min,2005.000000,2.375000,6.635000,0.290000,32.300000,0.258000,-0.335000,0.035000,0.322000,0.083000
25%,2010.000000,4.640000,8.464000,0.749750,58.685000,0.647000,-0.113000,0.690000,0.625500,0.206000
50%,2013.000000,5.386000,9.460000,0.835500,65.200000,0.763000,-0.025500,0.802000,0.722000,0.258000
75%,2017.000000,6.283000,10.353000,0.905000,68.590000,0.856000,0.091000,0.872000,0.799000,0.320000
max,2020.000000,8.019000,11.648000,0.987000,77.100000,0.985000,0.698000,0.983000,0.944000,0.705000

In [35]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['country_name', 'year', 'life_ladder', 'log_gdp_per_capita',
       'social_support', 'healthy_life_expectancy_at_birth',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption', 'positive_affect', 'negative_affect'],
      dtype='object')

In [36]:
df

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [37]:
df.isnull()

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1944,False,False,False,False,False,False,False,False,False,False,False
1945,False,False,False,False,False,False,False,False,False,False,False
1946,False,False,False,False,False,False,False,False,False,False,False
1947,False,False,False,False,False,False,False,False,False,False,False
1948,False,False,False,False,False,False,False,False,False,False,False

In [38]:
df.isnull().sum()

country_name                          0
year                                  0
life_ladder                           0
log_gdp_per_capita                   36
social_support                       13
healthy_life_expectancy_at_birth     55
freedom_to_make_life_choices         32
generosity                           89
perceptions_of_corruption           110
positive_affect                      22
negative_affect                      16
dtype: int64

In [39]:
import pandas as pd

df = pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [40]:
df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [41]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [42]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['country_name', 'year', 'life_ladder', 'log_gdp_per_capita',
       'social_support', 'healthy_life_expectancy_at_birth',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption', 'positive_affect', 'negative_affect'],
      dtype='object')

In [43]:
important_cols = [
    'life_ladder',
    'log_gdp_per_capita',
    'social_support',
    'healthy_life_expectancy_at_birth',
    'freedom_to_make_life_choices'
]

for col in important_cols:
    df[col] = df[col].fillna(df[col].mean())

In [44]:
df.isnull().sum()

country_name                          0
year                                  0
life_ladder                           0
log_gdp_per_capita                    0
social_support                        0
healthy_life_expectancy_at_birth      0
freedom_to_make_life_choices          0
generosity                           89
perceptions_of_corruption           110
positive_affect                      22
negative_affect                      16
dtype: int64

In [45]:
df['generosity'] = df['generosity'].fillna(df['generosity'].mean())
df['perceptions_of_corruption'] = df['perceptions_of_corruption'].fillna(df['perceptions_of_corruption'].mean())

In [46]:
df=df.dropna()

In [47]:
df.isnull().sum()

country_name                        0
year                                0
life_ladder                         0
log_gdp_per_capita                  0
social_support                      0
healthy_life_expectancy_at_birth    0
freedom_to_make_life_choices        0
generosity                          0
perceptions_of_corruption           0
positive_affect                     0
negative_affect                     0
dtype: int64

In [48]:
df.shape

(1925, 11)

In [49]:
df = df.drop_duplicates()

In [50]:
df

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [51]:
df.groupby('country_name')['life_ladder'].mean()

country_name
Afghanistan    3.594667
Albania        5.019385
Algeria        5.379286
Angola         4.420250
Argentina      6.310133
                 ...
Venezuela      6.019867
Vietnam        5.315923
Yemen          3.912250
Zambia         4.551714
Zimbabwe       3.882600
Name: life_ladder, Length: 164, dtype: float64

In [52]:
df.groupby('country_name').size()

country_name
Afghanistan    12
Albania        13
Algeria         7
Angola          4
Argentina      15
               ..
Venezuela      15
Vietnam        13
Yemen          12
Zambia         14
Zimbabwe       15
Length: 164, dtype: int64

In [53]:
df.groupby('country_name')['life_ladder'].agg(['mean', 'min', 'max'])

                  mean    min    max
country_name
Afghanistan   3.594667  2.375  4.758
Albania       5.019385  4.511  5.867
Algeria       5.379286  4.745  6.355
Angola        4.420250  3.795  5.589
Argentina     6.310133  5.793  6.776
...                ...    ...    ...
Venezuela     6.019867  4.041  7.478
Vietnam       5.315923  5.023  5.767
Yemen         3.912250  2.983  4.809
Zambia        4.551714  3.307  5.260
Zimbabwe      3.882600  2.694  4.955

[164 rows x 3 columns]

In [54]:
df.groupby(['country_name', 'year'])['life_ladder'].mean().reset_index()

     country_name  year  life_ladder
0     Afghanistan  2008        3.724
1     Afghanistan  2009        4.402
2     Afghanistan  2010        4.758
3     Afghanistan  2011        3.832
4     Afghanistan  2012        3.783
...           ...   ...          ...
1920     Zimbabwe  2016        3.735
1921     Zimbabwe  2017        3.638
1922     Zimbabwe  2018        3.616
1923     Zimbabwe  2019        2.694
1924     Zimbabwe  2020        3.160

[1925 rows x 3 columns]

In [55]:
df.groupby('country_name')['life_ladder'].mean().reset_index()

    country_name  life_ladder
0    Afghanistan     3.594667
1        Albania     5.019385
2        Algeria     5.379286
3         Angola     4.420250
4      Argentina     6.310133
..           ...          ...
159    Venezuela     6.019867
160      Vietnam     5.315923
161        Yemen     3.912250
162       Zambia     4.551714
163     Zimbabwe     3.882600

[164 rows x 2 columns]

In [56]:
df.groupby('year')['life_ladder'].mean().reset_index()

    year  life_ladder
0   2005     6.564200
1   2006     5.202886
2   2007     5.430772
3   2008     5.417139
4   2009     5.461496
5   2010     5.499175
6   2011     5.414228
7   2012     5.443754
8   2013     5.390437
9   2014     5.375085
10  2015     5.397197
11  2016     5.399479
12  2017     5.462363
13  2018     5.507743
14  2019     5.578685
15  2020     5.859181

In [57]:
df.groupby('country_name')[['log_gdp_per_capita','life_ladder']].mean()

              log_gdp_per_capita  life_ladder
country_name
Afghanistan             7.650833     3.594667
Albania                 9.384385     5.019385
Algeria                 9.334857     5.379286
Angola                  8.990000     4.420250
Argentina              10.033800     6.310133
...                          ...          ...
Venezuela               9.457757     6.019867
Vietnam                 8.638308     5.315923
Yemen                   8.313659     3.912250
Zambia                  8.066857     4.551714
Zimbabwe                7.850333     3.882600

[164 rows x 2 columns]

In [58]:
df

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [59]:
df.isnull().sum()

country_name                        0
year                                0
life_ladder                         0
log_gdp_per_capita                  0
social_support                      0
healthy_life_expectancy_at_birth    0
freedom_to_make_life_choices        0
generosity                          0
perceptions_of_corruption           0
positive_affect                     0
negative_affect                     0
dtype: int64

In [60]:
df.dropna()

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [61]:
df.isnull().sum()

country_name                        0
year                                0
life_ladder                         0
log_gdp_per_capita                  0
social_support                      0
healthy_life_expectancy_at_birth    0
freedom_to_make_life_choices        0
generosity                          0
perceptions_of_corruption           0
positive_affect                     0
negative_affect                     0
dtype: int64

In [62]:
df.sort_values(by="life_ladder")

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
11,Afghanistan,2019,2.375,7.697,0.420,52.40,0.394,-0.108000,0.924,0.351,0.502
9,Afghanistan,2017,2.662,7.697,0.491,52.80,0.427,-0.121000,0.954,0.496,0.371
1667,Syria,2013,2.688,8.396,0.585,58.76,0.455,0.225000,0.663,0.387,0.622
311,Central African Republic,2016,2.693,6.785,0.290,44.90,0.624,0.033000,0.859,0.579,0.494
10,Afghanistan,2018,2.694,7.692,0.508,52.60,0.374,-0.094000,0.928,0.424,0.405
...,...,...,...,...,...,...,...,...,...,...,...
450,Denmark,2007,7.834,10.891,0.954,69.92,0.932,0.240000,0.206,0.828,0.194
561,Finland,2018,7.858,10.783,0.962,71.90,0.938,-0.127000,0.199,0.782,0.182
563,Finland,2020,7.889,10.750,0.962,72.10,0.962,-0.116000,0.164,0.744,0.193
451,Denmark,2008,7.971,10.880,0.954,70.08,0.970,0.272000,0.248,0.757,0.163
449,Denmark,2005,8.019,10.851,0.972,69.60,0.971,0.000103,0.237,0.860,0.154

In [66]:
df.to_csv("cleaned_data.csv")

In [65]:
df

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [67]:
df.isnull().sum()

country_name                        0
year                                0
life_ladder                         0
log_gdp_per_capita                  0
social_support                      0
healthy_life_expectancy_at_birth    0
freedom_to_make_life_choices        0
generosity                          0
perceptions_of_corruption           0
positive_affect                     0
negative_affect                     0
dtype: int64